language: elixir
sudo: false
cache:
  directories:
    - priv/plts
elixir:
  - 1.9
otp_release:
  - 22.2
before_script:
  - mix deps.get
script: make test/all
env:
  - MIX_ENV=test
notifications:
  recipients:
    - travis@coryodaniel.com
jobs:
  include:
    - stage: coverage
      script: mix coveralls.travis
